# ERA5 Madagascar pipeline — simple, linear steps.
pipeline:
  name: era5_madagascar
  steps:
    - id: extract
      run: python src/extract.py
      env:
        ERA5_INPUT: s3://chi-lake/dev/bronze/madagascar/era5/hourly/  # or local path
    - id: daily_agg
      needs: [extract]
      run: python src/daily_agg.py
      env:
        OUTPUT_DIR: analytics/madagascar/outputs/era5_daily/